apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: bwce-template-db
  title: BWCE Template (Database) V1
  description: Create a new BWCE project with Documentation, that exposes a configured database table.
  tags:
    - recommended
    - bwce
    - tibco
    - postgres
    - database
    - table exposure
spec:
  owner: ACME
  type: service

  parameters:
    - title: Provide Database Details
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the BWCE Project
          ui:field: EntityNamePicker
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: A description for the BWCE Project
        returnprop:
          title: Return Value
          type: string
          description: The value that the BWCE Project should return
          default: 'https://www.example.com'
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        password:
          title: Password
          type: string
          ui:widget: password # will print '******' as value for property 'password' on Review Step
        masked:
          title: Masked
          type: string
          ui:backstage:
            review:
              mask: '<some-value-to-show>' # will print '<some-value-to-show>' as value for property 'Masked' on Review Step
        hidden:
          title: Hidden
          type: string
          ui:backstage:
            review:
              show: false # won't print any info about 'hidden' property on Review Step


    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  # This template is meant to be used on top of an existing template.
  # By adding the following and fetching from an absolute URL you can
  # add in the docs template
  steps:
    - id: fetch
      name: BWCE Skeleton
      action: fetch:template
      input:
        url: ./skeleton-hw
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}
          returnprop: ${{ parameters.returnprop }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

    - id: jenkinsEarBuild
      name: Trigger Jenkins EAR Build
      action: tibco:jenkins-trigger-ear-build
      input:
        name: ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
      - title: Open Jenkins Job
        icon: dashboard
        url: ${{ steps.jenkinsEarBuild.output.jobLink }}
